#!/bin/bash
set -euo pipefail

# 色付き出力
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Terraform Setup Script${NC}"
echo -e "${BLUE}========================================${NC}"

# AWS認証チェック
echo -e "\n${YELLOW}[1/4] AWS認証を確認中...${NC}"
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo "❌ AWS認証に失敗しました。aws configure を実行してください。"
    exit 1
fi
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "✅ AWS Account: ${GREEN}${ACCOUNT_ID}${NC}"

# GitHub リポジトリの設定
echo -e "\n${YELLOW}[2/4] GitHubリポジトリを設定中...${NC}"
if [ -n "${GITHUB_REPOSITORY:-}" ]; then
    REPO="$GITHUB_REPOSITORY"
else
    # git remote から取得を試みる
    if git remote get-url origin > /dev/null 2>&1; then
        REMOTE_URL=$(git remote get-url origin)
        # SSH形式: git@github.com:owner/repo.git
        # HTTPS形式: https://github.com/owner/repo.git
        REPO=$(echo "$REMOTE_URL" | sed -E 's#(git@github\.com:|https://github\.com/)##' | sed 's/\.git$//')
        echo -e "✅ Gitリモートから検出: ${GREEN}${REPO}${NC}"
    else
        read -p "GitHubリポジトリを入力してください (owner/repo): " REPO
    fi
fi

if [ -z "$REPO" ]; then
    echo "❌ GitHubリポジトリが指定されていません。"
    exit 1
fi
echo -e "✅ GitHub Repository: ${GREEN}${REPO}${NC}"

# OIDC Provider の存在確認
echo -e "\n${YELLOW}[3/4] GitHub OIDC Providerを確認中...${NC}"
OIDC_ARN="arn:aws:iam::${ACCOUNT_ID}:oidc-provider/token.actions.githubusercontent.com"

if aws iam get-open-id-connect-provider --open-id-connect-provider-arn "$OIDC_ARN" > /dev/null 2>&1; then
    CREATE_OIDC="false"
    echo -e "✅ 既存のOIDC Providerを検出: ${GREEN}既存を使用${NC}"
else
    CREATE_OIDC="true"
    echo -e "✅ OIDC Providerが存在しません: ${GREEN}新規作成${NC}"
fi

# terraform.tfvars の生成
echo -e "\n${YELLOW}[4/4] terraform.tfvars を生成中...${NC}"
cat > terraform.tfvars << EOF
# Auto-generated by setup.sh at $(date)
github_repository    = "${REPO}"
create_oidc_provider = ${CREATE_OIDC}
EOF

echo -e "✅ terraform.tfvars を生成しました"

# 結果サマリー
echo -e "\n${BLUE}========================================${NC}"
echo -e "${GREEN}セットアップ完了！${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "生成された terraform.tfvars:"
echo "─────────────────────────────"
cat terraform.tfvars
echo "─────────────────────────────"
echo ""
echo "次のステップ:"
echo "  1. backend.tf を設定: cp backend.tf.example backend.tf && vi backend.tf"
echo "  2. 初期化: terraform init"
echo "  3. 確認: terraform plan"
echo "  4. 適用: terraform apply"
